"""
Install Plan Generator

Produces the 5-file install pack:
  - install.md  (human-readable steps)
  - install.sh  (executable script)
  - values.yaml (configuration)
  - validate.sh (post-install verification)
  - rollback.sh (undo script)

The model generates content for these files; this module provides
the templates and structure.
"""

from __future__ import annotations

import os
from dataclasses import dataclass, field
from pathlib import Path
from textwrap import dedent


@dataclass
class InstallPlan:
    """A complete install plan with all 5 required files."""

    component_name: str
    namespace: str = "default"
    install_md: str = ""
    install_sh: str = ""
    values_yaml: str = ""
    validate_sh: str = ""
    rollback_sh: str = ""

    def save(self, output_dir: str | Path) -> Path:
        """Save all install plan files to a directory.

        Args:
            output_dir: Directory to save files in (created if needed).

        Returns:
            Path to the output directory.
        """
        out = Path(output_dir) / f"install-{self.component_name}"
        out.mkdir(parents=True, exist_ok=True)

        files = {
            "install.md": self.install_md,
            "install.sh": self.install_sh,
            "values.yaml": self.values_yaml,
            "validate.sh": self.validate_sh,
            "rollback.sh": self.rollback_sh,
        }

        for filename, content in files.items():
            filepath = out / filename
            filepath.write_text(content, encoding="utf-8")
            # Make .sh files executable
            if filename.endswith(".sh"):
                filepath.chmod(filepath.stat().st_mode | 0o755)

        return out

    def to_markdown(self) -> str:
        """Render the full install plan as a single Markdown document."""
        sections = [
            f"# Install Plan: {self.component_name}\n",
            f"**Namespace**: `{self.namespace}`\n",
            "---\n",
            "## install.md\n",
            self.install_md or "_Not generated yet._",
            "\n---\n",
            "## install.sh\n",
            f"```bash\n{self.install_sh}\n```" if self.install_sh else "_Not generated yet._",
            "\n---\n",
            "## values.yaml\n",
            f"```yaml\n{self.values_yaml}\n```" if self.values_yaml else "_Not generated yet._",
            "\n---\n",
            "## validate.sh\n",
            f"```bash\n{self.validate_sh}\n```" if self.validate_sh else "_Not generated yet._",
            "\n---\n",
            "## rollback.sh\n",
            f"```bash\n{self.rollback_sh}\n```" if self.rollback_sh else "_Not generated yet._",
        ]
        return "\n".join(sections)


# ─── Templates ───────────────────────────────────────────────────────────────

INSTALL_MD_TEMPLATE = dedent("""\
    # Install Guide: {component_name}

    ## Prerequisites
    - Kubernetes cluster >= {k8s_version_min}
    - Helm >= 3.x installed
    - kubectl configured and connected
    - Sufficient cluster resources (see values.yaml for requirements)

    ## Steps

    ### 1. Create Namespace
    ```bash
    kubectl create namespace {namespace} --dry-run=client -o yaml | kubectl apply -f -
    ```

    ### 2. Add Helm Repository
    ```bash
    {helm_repo_add}
    helm repo update
    ```

    ### 3. Review Configuration
    Review `values.yaml` and adjust for your environment:
    - Resource requests/limits
    - Storage class
    - Node selectors / tolerations
    - Ingress configuration

    ### 4. Install
    ```bash
    bash install.sh
    ```

    ### 5. Validate
    ```bash
    bash validate.sh
    ```

    ### 6. If Something Goes Wrong
    ```bash
    bash rollback.sh
    ```

    ## Post-Install
    {post_install_notes}
""")

INSTALL_SH_TEMPLATE = dedent("""\
    #!/usr/bin/env bash
    # Install script for {component_name}
    # Generated by K8s/Helm Support Copilot
    #
    # Usage: bash install.sh
    # Requires: helm 3.x, kubectl

    set -euo pipefail

    NAMESPACE="{namespace}"
    RELEASE_NAME="{release_name}"
    CHART="{chart_ref}"
    VALUES_FILE="$(dirname "$0")/values.yaml"

    echo "=== Installing {component_name} ==="
    echo "Namespace: $NAMESPACE"
    echo "Release:   $RELEASE_NAME"
    echo ""

    # Step 1: Ensure namespace exists
    echo "[1/4] Creating namespace..."
    kubectl create namespace "$NAMESPACE" --dry-run=client -o yaml | kubectl apply -f -

    # Step 2: Add Helm repo
    echo "[2/4] Adding Helm repository..."
    {helm_repo_add}
    helm repo update

    # Step 3: Install/Upgrade
    echo "[3/4] Installing {component_name}..."
    helm upgrade --install "$RELEASE_NAME" "$CHART" \\
      --namespace "$NAMESPACE" \\
      --values "$VALUES_FILE" \\
      --wait \\
      --timeout 5m

    # Step 4: Quick check
    echo "[4/4] Quick validation..."
    kubectl get pods -n "$NAMESPACE" -l app.kubernetes.io/instance="$RELEASE_NAME"

    echo ""
    echo "=== Installation complete ==="
    echo "Run 'bash validate.sh' for full verification."
""")

VALIDATE_SH_TEMPLATE = dedent("""\
    #!/usr/bin/env bash
    # Validation script for {component_name}
    # Generated by K8s/Helm Support Copilot
    #
    # Usage: bash validate.sh

    set -euo pipefail

    NAMESPACE="{namespace}"
    RELEASE_NAME="{release_name}"
    PASS=0
    FAIL=0

    check() {{
      local desc="$1"
      shift
      echo -n "  [$desc] ... "
      if "$@" > /dev/null 2>&1; then
        echo "PASS"
        ((PASS++))
      else
        echo "FAIL"
        ((FAIL++))
      fi
    }}

    echo "=== Validating {component_name} ==="
    echo ""

    echo "--- Helm Release ---"
    check "Release exists" helm status "$RELEASE_NAME" -n "$NAMESPACE"

    echo ""
    echo "--- Pods ---"
    check "Pods running" kubectl wait --for=condition=Ready pod \\
      -l app.kubernetes.io/instance="$RELEASE_NAME" \\
      -n "$NAMESPACE" --timeout=120s

    echo ""
    echo "--- Services ---"
    check "Service exists" kubectl get svc -n "$NAMESPACE" \\
      -l app.kubernetes.io/instance="$RELEASE_NAME"

    {extra_checks}

    echo ""
    echo "=== Results: $PASS passed, $FAIL failed ==="
    if [ "$FAIL" -gt 0 ]; then
      echo "Some checks failed. Review the output above."
      exit 1
    fi
""")

ROLLBACK_SH_TEMPLATE = dedent("""\
    #!/usr/bin/env bash
    # Rollback script for {component_name}
    # Generated by K8s/Helm Support Copilot
    #
    # Usage: bash rollback.sh [--delete]
    #   --delete  Completely remove the release (default: rollback to previous)

    set -euo pipefail

    NAMESPACE="{namespace}"
    RELEASE_NAME="{release_name}"

    echo "=== Rollback: {component_name} ==="

    if [ "${{1:-}}" = "--delete" ]; then
      echo "Mode: FULL DELETE"
      echo ""
      echo "This will remove the Helm release and all its resources."
      read -p "Are you sure? (yes/no): " confirm
      if [ "$confirm" != "yes" ]; then
        echo "Aborted."
        exit 0
      fi

      echo "[1/2] Uninstalling Helm release..."
      helm uninstall "$RELEASE_NAME" -n "$NAMESPACE"

      echo "[2/2] Cleaning up namespace (optional)..."
      echo "  To delete namespace: kubectl delete namespace $NAMESPACE"

    else
      echo "Mode: ROLLBACK TO PREVIOUS REVISION"
      echo ""

      echo "Current release info:"
      helm history "$RELEASE_NAME" -n "$NAMESPACE" --max 5

      echo ""
      echo "[1/1] Rolling back..."
      helm rollback "$RELEASE_NAME" -n "$NAMESPACE" --wait --timeout 5m

      echo ""
      echo "Post-rollback status:"
      helm status "$RELEASE_NAME" -n "$NAMESPACE"
    fi

    echo ""
    echo "=== Rollback complete ==="
    echo "Run 'bash validate.sh' to verify."
""")

DEFAULT_VALUES_YAML = dedent("""\
    # values.yaml for {component_name}
    # Generated by K8s/Helm Support Copilot
    #
    # Review and adjust these values for your environment.

    # --- Image ---
    image:
      repository: {image_repo}
      tag: {image_tag}
      pullPolicy: IfNotPresent

    # --- Resources ---
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

    # --- Replicas ---
    replicaCount: 1

    # --- Service ---
    service:
      type: ClusterIP
      port: 80

    # --- Node Selection (uncomment as needed) ---
    # nodeSelector: {{}}
    # tolerations: []
    # affinity: {{}}

    # --- Storage (uncomment if needed) ---
    # persistence:
    #   enabled: false
    #   storageClass: ""
    #   size: 10Gi
""")


# ─── Well-known component configs ────────────────────────────────────────────

KNOWN_COMPONENTS = {
    "nginx-ingress": {
        "chart_ref": "ingress-nginx/ingress-nginx",
        "helm_repo_add": 'helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx',
        "release_name": "ingress-nginx",
        "image_repo": "registry.k8s.io/ingress-nginx/controller",
        "image_tag": "v1.9.5",
        "k8s_version_min": "v1.25",
        "post_install_notes": "Check the LoadBalancer/NodePort IP assigned to the ingress controller service.",
        "extra_checks": dedent("""\
            echo ""
            echo "--- Ingress Class ---"
            check "IngressClass exists" kubectl get ingressclass nginx
        """),
    },
    "cert-manager": {
        "chart_ref": "jetstack/cert-manager",
        "helm_repo_add": 'helm repo add jetstack https://charts.jetstack.io',
        "release_name": "cert-manager",
        "image_repo": "quay.io/jetstack/cert-manager-controller",
        "image_tag": "v1.14.3",
        "k8s_version_min": "v1.25",
        "post_install_notes": "Create a ClusterIssuer for Let's Encrypt (or your CA).",
        "extra_checks": dedent("""\
            echo ""
            echo "--- CRDs ---"
            check "CRDs installed" kubectl get crd certificates.cert-manager.io
        """),
    },
    "prometheus": {
        "chart_ref": "prometheus-community/kube-prometheus-stack",
        "helm_repo_add": 'helm repo add prometheus-community https://prometheus-community.github.io/helm-charts',
        "release_name": "kube-prometheus",
        "image_repo": "quay.io/prometheus/prometheus",
        "image_tag": "v2.49.1",
        "k8s_version_min": "v1.25",
        "post_install_notes": "Access Grafana via port-forward: kubectl port-forward svc/kube-prometheus-grafana 3000:80",
        "extra_checks": dedent("""\
            echo ""
            echo "--- Prometheus CRDs ---"
            check "ServiceMonitor CRD" kubectl get crd servicemonitors.monitoring.coreos.com
        """),
    },
    "argocd": {
        "chart_ref": "argo/argo-cd",
        "helm_repo_add": 'helm repo add argo https://argoproj.github.io/argo-helm',
        "release_name": "argocd",
        "image_repo": "quay.io/argoproj/argocd",
        "image_tag": "v2.10.1",
        "k8s_version_min": "v1.26",
        "post_install_notes": "Get admin password: kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath='{.data.password}' | base64 -d",
        "extra_checks": dedent("""\
            echo ""
            echo "--- ArgoCD CRDs ---"
            check "Application CRD" kubectl get crd applications.argoproj.io
        """),
    },
}


def generate_install_plan(
    component_name: str,
    namespace: str = "default",
    llm_values_yaml: str | None = None,
    llm_extra_notes: str | None = None,
) -> InstallPlan:
    """Generate a complete install plan for a K8s component.

    Uses known component configurations when available,
    falls back to generic templates otherwise.

    Args:
        component_name: The component to install.
        namespace: Target namespace.
        llm_values_yaml: LLM-generated values.yaml content (overrides template).
        llm_extra_notes: Additional notes from the LLM.

    Returns:
        Complete InstallPlan with all 5 files.
    """
    # Look up known component, or use defaults
    config = KNOWN_COMPONENTS.get(component_name, {})

    chart_ref = config.get("chart_ref", f"{component_name}/{component_name}")
    helm_repo_add = config.get(
        "helm_repo_add",
        f"helm repo add {component_name} https://charts.example.com/{component_name}"
    )
    release_name = config.get("release_name", component_name)
    image_repo = config.get("image_repo", f"docker.io/library/{component_name}")
    image_tag = config.get("image_tag", "latest")
    k8s_version_min = config.get("k8s_version_min", "v1.25")
    post_install_notes = config.get("post_install_notes", "Verify the deployment is healthy.")
    extra_checks = config.get("extra_checks", "")

    if llm_extra_notes:
        post_install_notes += f"\n\n{llm_extra_notes}"

    fmt = dict(
        component_name=component_name,
        namespace=namespace,
        release_name=release_name,
        chart_ref=chart_ref,
        helm_repo_add=helm_repo_add,
        image_repo=image_repo,
        image_tag=image_tag,
        k8s_version_min=k8s_version_min,
        post_install_notes=post_install_notes,
        extra_checks=extra_checks,
    )

    plan = InstallPlan(
        component_name=component_name,
        namespace=namespace,
        install_md=INSTALL_MD_TEMPLATE.format(**fmt),
        install_sh=INSTALL_SH_TEMPLATE.format(**fmt),
        values_yaml=llm_values_yaml or DEFAULT_VALUES_YAML.format(**fmt),
        validate_sh=VALIDATE_SH_TEMPLATE.format(**fmt),
        rollback_sh=ROLLBACK_SH_TEMPLATE.format(**fmt),
    )

    return plan
